apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-map
data:
  APP_MODE: dev
  APP_COLOR: blue

---

apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  DB_USER: ZGVtbwo=
  DB_PASS: c2VjcmV0MTIzCg==

---

apiVersion: v1
kind: Pod
metadata:
  name: busybox-conf-map-test
  labels:
    app: busybox-conf-map-test
spec:
  containers:
    - name: busybox-conf-map-test
      image: busybox
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -c
        - 'env | grep APP_ ; cat /etc/secrets/DB_PASS;'
      env:
        - name: APP_MODE
          valueFrom:
            configMapKeyRef:
              name: app-config-map
              key: APP_MODE
        - name: APP_COLOR
          valueFrom:
            configMapKeyRef:
              name: app-config-map
              key: APP_COLOR
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secrets"
  volumes:
    - name: secret-volume
      secret:
        secretName: app-secret

  restartPolicy: Always